#MAKEFILES = make1 make2


all : ec1 mak1 

ec1 :
	@echo "in Make"

mak1 :
	@$(MAKE) -C make1 		#MAKE has same effect as using '+'	
#	@+make -C make1			# '+' wont work here
#	@cd make1 && $(MAKE)
		

#mk2 :
#	@$(MAKE) -C make2
