app: switch5.c assn_5_1.c assn_5_2.c assn_5_3.c assn_5_4.c assn_5_5.c assn_5_6.c mystrlen.c mystrstr.c
	gcc -o app -Wall switch5.c assn_5_1.c assn_5_2.c assn_5_3.c assn_5_4.c assn_5_5.c assn_5_6.c mystrlen.c mystrstr.c
